Fix missing awaits for enquirer.prompt
Running `pnpm install-completions` causes the following output.

```
✔ Which Shell do you use ? · fish
Very well, we will install using undefined
? Which path then ? Must be absolute. ‣ ? We will install completion to ~/.config/fish/config.fish, is it ok ? (y/$HOME/.local/share/npm/lib/node_modules/pnpm/dist/pnpm.js:8450
      throw new Error("options.location is required");
            ^

Error: options.location is required
    at Object.install ($HOME/.local/share/npm/lib/node_modules/pnpm/dist/pnpm.js:8450:13)
    at install ($HOME/.local/share/npm/lib/node_modules/pnpm/dist/pnpm.js:8557:21)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async $HOME/.local/share/npm/lib/node_modules/pnpm/dist/pnpm.js:123194:7
```

Only one of the prompts in the file `lib/prompt.js` is actually awaited. This PR fixes the rest.